parameters:
#    epiphany_test.example.class: Epiphany\TestBundle\Example

services:
#    epiphany_test.example:
#        class: %epiphany_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
